package com.practice;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;



public class a{
public static void main(String [] args){

ArrayList<String> list = new ArrayList<String>();

list.add("a");
list.add("b");
list.add("c");


for(int i =0 ;i<list.size()-1;i++){


//System.out.println(list.get(i));


}
System.out.println(Integer.MIN_VALUE);
checkString("ACAAAAATAAACAAAAACAAAAAAAAAATAAATACAATAAAAAAAAAAAATGAAATACAACAACAAATAAAATAAAAACGACTAAAAAATAAAAAAAAAAAAAAAAAGAGTACTAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAACACAATCAAAATAAACAAAAAAAAAAAAACCAAAATAATCAACAAAAAAAAAAAAAACAAAAACAACAACAAACAAAAAAAAACACAAACAAAAAAAAAAAAAAAACAAAACAAACAAAAAAAAAAAAACAAAAAAACAAAAAAAAAAAAAAAAACAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAACAAACAAAAAAAAAAAATACAAAAAGCTATAAAAAAAAAAAAATTAAAAAACAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAGAAAAACAAAAAAAAAAAAAAAAACAACCAAAAAACAAAAAAAAACTAAAAAAAAAAAAAAAAAAAAAAAAAAATAACAAAAAACACAAAAAAAAAAAAGAAAGAAAAAAAACACAAAAAAAAACAAACAAAAAAAAAAAAAAAAAAAGAAAACAAAAAAACAAAAAAAACAAAAAAAAAACAAAAATTGGACAAAAAAAAACAAAAAAAAAAAACAAAAAAAGTAAAACAAATAAAAAAACAAAAAAAACAAAAAAAAAAAAAAAAAACAAAAAAGAAACAAAAAACAAAAAAAAATAACAAAACCAAAAAACAAATAAAAAACAAAAAAAATAACACAAAAAAAAAAAGAAACAAAAAAAAAAAAAAAAAAAAAAATTATAAAAAAAAAAAAAAAACAAAAAAAAAAAAAACAAAAAAAAAAGGAAAAAAAAAAAAAAAAAAAAAAAAAAATAACTAAACAAAAAAAAACAAACAAAAAATCAAAAAAAAAAAAGAAAAAAGAATAAGCAACAAAAACACAAAAAAAAAAAAAAAAAAAAAAAACATAAACAATAATAAAAAAAAAACAAAAAAAACAAAAGAACAACAAAAAACAAAACTAAACAAATAAAAAAAAAAAAACAAAAACTACAAAAAAAAAAAGAAAAAAAAAGAAAAAAAAACAAATAAAAGAAAAAAAAAAAAAAAAAAAACACAAAAAAAAAAATAAAAAAAAAAAAAAAAACAAAATAAACAAAAACAAAGAAAAAAACAAACAAAAAAAAAAAACAAAAAACTAAAAACAAAAAAAAAACAAAACACAAAAAAAAAAAAAAATAAAAAAAAAACAAAAAAACAAAAAGGAAAAAAAAAAAAGAACAAAAAAAAAAACAACAGAAAAAAGAAAAGAAAAAAAAAAAAAGACCACAAAATAAAAAAAAACAACAAACAAAAAAAAACAAAACAAAAAAACGAACAAAAAAAACAAAAACAAAAAAAAAAAAAAAAAAAAAAAGGCAAAAACAAAAAAAACAAAACAAAACAAAAAAACAAAAAAAAATTAAGATAAAGAACAAAAAAAGAAGAGAAAAAATTAACAAAAAAAAAAAAATAAAAAATACAAAAAGAAATAAAAAATACAACACACAACAAAAACGAAAAAAAAAAAAAAAACACAAAATAGAAAAAAAAAAAAAACAAAAAAAAAAAAAAGAAAAAAACAAAAAAAAAAAAATAAAAAAAAACGACACAGAAACAAAAAATAACAAAAAAAAAAAAAATAAAAAAAAAACAAAAAAAAAACAAAAAATAAAAAAAAAAACAAACAAAAAAAAAAAAAAAATAAAAAAAAAAAAAGCAAAACATAAACAAGAAAAAAAAAAAAAGTACAAATAACAAAACAAAAAAGACACTAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAACCACAAAACAAAAAAATAAAGCAAAAAAAAAAAAAAAAAAAAAAAAAAAATAAATGAAAAAAAAAAGAAAACCAAAAAAATAAAAGA");

//rotLeft(new int[] {33, 47, 70, 37, 8, 53, 13, 93, 71, 72, 51, 100, 60, 87, 97},13);

}

static int[] rotLeft(int[] a, int d) {
int count=0;
for(int i=a.length-1 ;i>a.length-d-1;i--){

  int c =0;
if(i-d>=0) {
  c=a[i];
    a[i]=a[i-d];
a[i-d]=c;
}
else {
    c=a[i];
    a[i]=a[a.length-count-1];
    a[a.length-count-1]=c;
    count++;
    
}
for(int j=0;j<a.length;j++) 
	System.out.print( a[j] +" ");
System.out.println("");

}
System.out.println("final");
for(int j=0;j<a.length;j++) {
	
	System.out.print(a[j] + " ");
}
return a;
}


static void checkString(String input) {
	
	char[] check=input.toCharArray();
	Map<Character,Integer> map= new HashMap<Character,Integer>();
	
	for(int i=0;i<check.length;i++ ) {
		
		if(map.containsKey(check[i])) {
			
			map.put(check[i], map.get(check[i])+1);
		}
		
		else {
			
			map.put(check[i], 1);
		}
		
	}
	//int index=0;
	//Boolean value=false;
	//String finalString="";
	int result =0;
	char char1 = 0;
	Map <Character,Integer> map1=new HashMap<Character,Integer>();
	for(Map.Entry<Character, Integer> entry : map.entrySet()){
		
		if(entry.getValue()>check.length/4) {
			
			result=check.length/4>entry.getValue()?0:entry.getValue()-check.length/4;
			char1=entry.getKey();
			
		}
		map1.put(char1, result);
	}
	int count1=0;
	ArrayList<Character> arr=new ArrayList<Character>();
	for(int i=0;i<check.length;i++ ) {
		if(char1==check[i]) {
			count1++;
		
			
		}
		if(count1 >0 && count1 <=result) {
			arr.add(check[i]);
		}
	}
	
	System.out.println(arr.size());
}
}